### ISSUE TITLE
Tuner results in error

### ISSUE THREAD

**Issue by rfaasicreative** [mattymoomoo/aws-power-tuner-ui#25] opened 2021-11-25 07:22 UTC
Hi, 

I already did some debugging. I think it's do to this change: https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/

Cloudwatch error:

`2021-11-25T07:20:03.843Z	687c79de-4a49-4dbb-b3cf-8302354ff3ac	ERROR	Invoke Error 	{
    "errorType": "ResourceConflictException",
    "errorMessage": "The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:eu-west-1:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "code": "ResourceConflictException",
    "message": "The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:eu-west-1:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "time": "2021-11-25T07:20:03.842Z",
    "requestId": "c63773db-f777-4379-9f33-7229708e555d",
    "statusCode": 409,
    "retryable": false,
    "retryDelay": 21.75168710443578,
    "stack": [
        "ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:eu-west-1:647702511981:function:GatewayService-Monitoring-Tools-dev-Update_LambdaReferences",
        "    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)"
    ]
}
`

Previous Clouwatch log line:

`2021-11-25T07:20:03.843Z	687c79de-4a49-4dbb-b3cf-8302354ff3ac	INFO	error during config creation for value 128
`

Input:

![image](https://user-images.githubusercontent.com/68738962/143397265-c0935b7c-2a48-414b-ba92-8c4eb6846122.png)

Kind regard,

Ruurd

**Comment by rwsender** [comment] 2021-11-26 11:44
This was caused by the UI not having the newest version of the tuner. I've opened a PR [here](https://github.com/mattymoomoo/aws-power-tuner-ui/pull/26) for this.

**Comment by mattymoomoo** [comment] 2021-11-26 15:09
This PR has now be merged if you wish to update.

**Closed by mattymoomoo** 2021-11-26 15:09 UTC

**Comment by dobeerman** [comment] 2023-05-10 09:35
The issue still persists. 

> Results
It appears something went wrong with the power tuning. Please verify your payload matches what the lambda expects and the ARN is located in the correct account. If you want to debug further, please navigate to the [AWS console](https://console.aws.amazon.com/console/home?#) viewing the executions of the power tuner using the Step Functions service.

No any additional info. The error appears immediately after the start button is clicked.
